config/routes.rb
Radio::Application.routes.draw do 
  devise_for :users

   resources :songs do
  member do
      get 'crop'
    end
  end
  get '/users/logout', :to => 'sessions#destroy'
  match '/auth/:provider/callback', :to => 'sessionsf#create'
  match '/auth/failure', :to => 'sessionsf#failure'
  match '/signout', to: 'sessionsf#destroy', as: 'signout'
get 'tags/:tag', to: 'songs#index', as: :tag
root :to => 'songs#index'
end

app/models/man.rb
class Man < ActiveRecord::Base
  attr_accessible :name, :oauth_expires_at, :oauth_token, :provider, :uid
def self.from_omniauth(auth)
  where(auth.slice(:provider, :uid)).first_or_initialize.tap do |man|
    man.provider = auth.provider
    man.uid = auth.uid
    man.name = auth.info.name
    man.oauth_token = auth.credentials.token
    man.oauth_expires_at = Time.at(auth.credentials.expires_at)
    man.save!
  end
end

end

app/models/song.rb
# -*- coding: utf-8 -*-
class Song < ActiveRecord::Base

  attr_accessible :album, :author, :length, :length_min, :title, :year, :tag_list,
     :cover, :remove_cover, :cover_cache, :remote_cover_url, :text_search 
  acts_as_taggable_on :tags
  has_attached_file :cover

def length_min
 t = Time.at(length).utc.strftime("%H:%M:%S") #=> "01:00:00"
return t
 end




def self.search(title)
if title.present?
    # SQLite
  find(:all, :conditions => ['Title like ?', "%#{title}%"])
    # PostgreSQL; i – ignore case
  # where("quotation ilike :q or source ilike :q", q: "%#{query}%")
  else
    scoped
  end
end
 def crop_cover
    cover.recreate_versions! if crop_x.present?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
private

def current_man
  @current_man ||= Man.find(session[:man_id]) if session[:man_id]
end
helper_method :current_man
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
def destroy
  sign_out
  redirect_to root_path
end
end

app/controllers/sessionsf_controller.rb
class SessionsfController < ApplicationController
  def create
    man = Man.from_omniauth(env["omniauth.auth"])
    session[:man_id] = man.id
    redirect_to root_url
  end

  def destroy
    session[:man_id] = nil
    redirect_to root_url
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  # GET /songs
  # GET /songs.json
 
def index
 
    
  if params[:tag]
    @songs = Song.tagged_with(params[:tag])
  else
   
    if params[:title]
      @songs = Song.search(params[:title])
    else
    @songs = Song.all
    end
  end

     respond_to do |format|
     format.html # index.html.erb
     format.json { render json: @songs }
    end
end

  # GET /songs/1
  # GET /songs/1.json
  def show
    @song = Song.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @song }
    end
  end

  # GET /songs/new
  # GET /songs/new.json
  def new
    @song = Song.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @song }
    end
  end
 def crop
    @song = Song.find(params[:id])
  end
  # GET /songs/1/edit
  def edit
    @song = Song.find(params[:id])
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(params[:song])

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render json: @song, status: :created, location: @song }
      else
        format.html { render action: "new" }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /songs/1
  # PUT /songs/1.json
  def update
    @song = Song.find(params[:id])

    respond_to do |format|
      if @song.update_attributes(params[:song])
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song = Song.find(params[:id])
    @song.destroy

    respond_to do |format|
      format.html { redirect_to songs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/fortunes/_form.html.erb
<%= form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br />
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :album %><br />
    <%= f.text_field :album %>
  </div>
  <div class="field">
    <%= f.label :year %><br />
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :length %><br />
    <%= f.number_field :length %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fortunes/edit.html.erb
<%- model_class = Fortune -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/fortunes/index.html.erb
<%- model_class = Fortune -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:quotation) %></th>
      <th><%= model_class.human_attribute_name(:source) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @fortunes.each do |fortune| %>
      <tr>
        <td><%= link_to fortune.id, fortune_path(fortune) %></td>
        <td><%= fortune.quotation %></td>
        <td><%= fortune.source %></td>
        <td><%=l fortune.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_fortune_path(fortune), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      fortune_path(fortune),
                      :method => :delete,

                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_fortune_path,
            :class => 'btn btn-primary' %>

app/views/fortunes/show.html.erb
<%- model_class = Fortune -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:quotation) %>:</strong></dt>
  <dd><%= @fortune.quotation %></dd>
  <dt><strong><%= model_class.human_attribute_name(:source) %>:</strong></dt>
  <dd><%= @fortune.source %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              fortunes_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_fortune_path(@fortune), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              fortune_path(@fortune),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Radio</title>

  <%= render partial: 'shared/navbar' %>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/fixed.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Radio" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
           <span class="icon-bar"></span>
            <span class="icon-bar"></span> 
          </a>
          <a class="brand" href="#">Radio</a>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <div class="row">
          <div class="span9">
             <%= yield %>
          </div>
          <div class="span3">
            <div class="well sidebar-nav">
              <h3>Sidebar</h3>
              <ul class="nav nav-list">
                <li class="nav-header">Sidebar</li>
                <li><%= link_to "Link1", "/path1"  %></li>
                <li><%= link_to "Link2", "/path2"  %></li>
                <li><%= link_to "Link3", "/path3"  %></li>
              </ul>
            </div><!--/.well -->
          </div><!--/span-->
        </div><!--/row-->

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/shared/_navbar.html.erb
<div class="navbar">
    <div class="navbar-inner">
        <div class="container">
            <a class="brand" href="/">Spis piosenek</a>
            <!--  <%= link_to "Link 1", "https://www.google.pl/" %>
 -->
            <ul class="nav pull-left">
                Radio Ruby
                <div id="man_nav">
                    <% if current_man %>
                    Signed in as <strong>
                        <%= current_man.name %></strong>!
                    <%= link_to "Sign out from Facebook", signout_path, id: "sign_out" %>
                    <% else %>
                    <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
                    <% end %>
                </div>
                <%= link_to "google", "https://www.google.pl/" %>
            </ul>
            <ul class="nav pull-right">
                <li><a class="brand" href="/users/sign_up">Rejestracja</a></li>
                <li>
                    <div id="login_logout">
                        <% unless user_signed_in? %>
                        <li><a class="brand" href="/users/sign_in">Logowanie</a></li>
                        <% else %>
                        <%= current_user.email %>
                </li>
                <%= link_to 'Sign Out Radio', "/users/logout" %>
                <% end %>
        </div>
        </ul>
    </div>
</div>

app/views/songs/_form.html.erb
<%= simple_form_for(@song, :html => { :multipart => true }) do |f| %>
  <%= f.error_notification %>


  <% unless @song.new_record? %>
    
  <% end %>
  
  
  <div class="form-inputs">
    <%= f.input :tag_list, :label => "Tags (separated by spaces)" %>
    <%= f.label :cover %><br />
    <%= f.file_field :cover %>    
    <%= f.input :title %>
    <%= f.input :author %>
    <%= f.input :album %>
    <%= f.input :year %>
    <%= f.input :length %>
  </div>
 <div class="control-group string optional">
    
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<h1>Editing song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<%- model_class = Song -%>
<div class="page-header">
 <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>

<%= form_tag songs_path, :method =>'get',id: "songs_search", class: "form-inline"  do %>
  <%= text_field_tag :title, params[:title] %>
  <%= submit_tag "Search", :name => nil %>
<% end %>



<div id="tag_cloud">
  <% tag_cloud Song.tag_counts, %w[s m l] do |tag, css_class| %>
    <%= link_to tag.name, tag_path(tag.name), class: css_class %>
  <% end %>
</div>


<table class="table table-striped">
     <thead>
  <tr>
  
    <th><%= model_class.human_attribute_name(:id) %></th>
    <th><%= model_class.human_attribute_name(:cover) %></th>
    <th><%= link_to "Title" %></th>
    <th><%= model_class.human_attribute_name(:author) %></th>
    <th><%= model_class.human_attribute_name(:album) %></th>
    <th><%= model_class.human_attribute_name(:year) %></th>
    <th><%= model_class.human_attribute_name(:length) %></th>
    <th><%= model_class.human_attribute_name(:tags) %></th>

    <th><%=t '.actions', :default => t("helpers.actions") %></th>
  
 
  </tr>
 </thead>
  <tbody>

<% @songs.each do |song| %>
  <tr>

    <th><%= song.id %></th>
    <td><%= image_tag  song.cover.url %></td>    
    <td><%= song.title %></td>
    <td><%= song.author %></td>
    <td><%= song.album %></td>
    <td><%= song.year %></td>
    <td><%= song.length_min %></td>
    <td><%= song.tag_list %></td>


    <td> <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_song_path(song), :class => 'btn btn-mini' %> 
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      song_path(song),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },                 
                      :class => 'btn btn-mini btn-danger' %>
</td>

  </tr>
<% end %>
 </tbody>
</table>


<p><%= link_to t('.new', default: t("helpers.links.new")), new_song_path, :class => 'btn btn-primary' %></p>

app/views/songs/new.html.erb
<h1>New song</h1>

<%= render 'form' %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Tags:</b>
  <%= @song.tag_list %>
</p>
<p>
  <b>Cover:</b>
<% if @song.cover? %>
  <%= image_tag @song.cover.url %>
  <br />
  <%= link_to @song.cover.url, @song.cover.url %>
<% end %>

</p> 
<p>
  <b>Title:</b>
  <%= @song.title %>
</p>

<p>
  <b>Author:</b>
  <%= @song.author %>
</p>

<p>
  <b>Album:</b>
  <%= @song.album %>
</p>

<p>
  <b>Year:</b>
  <%= @song.year %>
</p>

<p>
  <b>Length:</b>
  <%= @song.length_min %>
</p>


<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %>